### PR TITLE
Fix admin rights

### PR DESCRIPTION
**Pull request by mvgucht**
added isAllowed functions.

### CODE REVIEW

**Comment by hostep** [comment]
@mvguch can this get merged into master? So when someone (me) gets told to get the latest version, it actually works properly :)

**Comment by mvgucht** [comment]
oops. srr, I thought it was already merged...

**Comment by hostep** [comment]
Nice, that was quick, thanks!

**Comment by mvgucht** [comment]
@hostep: wait (!): I changed the master branch to version 2.0 yesterday because I switched it to DIS services (Benelux web services). So if you want to use it with the previous web services (Delicom) you'll need to make this adjustment in the delicom-ws branch.

https://github.com/DPDBeNeLux/magento-DPD_Shipping/tree/delicom-ws

sorry for the trouble

**Comment by mvgucht** [comment]
I just merged the admin rights fix into the delicom-ws branch.
please use this version:

https://github.com/DPDBeNeLux/magento-DPD_Shipping/tree/delicom-ws

**Pull request merged**
